### ISSUE TITLE
思源1.7.6中三级标题光标位置异常

### ISSUE THREAD

**Issue by choyy** [Achuan-2/siyuan-themes-tsundoku-dark#18]
主题在1.7.5版本似乎正常，更新1.7.6后输入三级标题后光标位置错误：
![图片](https://user-images.githubusercontent.com/68107073/150642121-302e8c62-65f4-4c6f-b230-d533096080d2.png)
green主题更明显些：
![图片](https://user-images.githubusercontent.com/68107073/150642147-8bc4d214-b9eb-43a7-b53c-7110b72ed30b.png)

**Comment by Achuan-2** [comment]
下个版本修复
 ```css
  /* 调整h3空行时光标位置 */
  .protyle-wysiwyg .h3>[spellcheck="false"]:empty {
      padding-left: 1rem;
  }
  ```
