### ISSUE TITLE
新版主题的代码块编号bug

### ISSUE THREAD

**Issue by netdog2019** [Achuan-2/siyuan-themes-tsundoku-dark#19]
![image](https://user-images.githubusercontent.com/49815951/150642146-5b197dc2-870b-41c9-9fac-d01c0357041a.png)
如图所示，代码块只要编号超过10，编号就会这样，但有时是按方向键会这样，上下左右方向键都会这样。
Tsundoku主题非常棒，感谢老铁~~~

**Comment by netdog2019** [comment]
今天再测试了一下，发现用默认字体不会出现这种情况，字号调大也不会。用霞婺文楷字体，字号大于16号就会出现这种情况。

**Comment by Achuan-2** [comment]
会不会是这个字体的问题呢，我用其他字体都没出现这个情况

**Comment by Achuan-2** [comment]
调整了padding-right就可以了，下个版本修复
```css
.protyle-linenumber__rows {
    margin-top: 31px !important;
    background-color:var(--b3-protyle-code-background);
    padding-right:10px;
    padding-bottom: 0px;
    margin-bottom: 0px;
    width: 39px;
}
```
